# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
    ]
