version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: arrow
    versions:
    - 0.17.0
    - 1.0.2
    - 1.0.3
  - dependency-name: django
    versions:
    - 2.2.13
